version: '3.8'

services:
  db:
    image: postgres:15.3-alpine
    container_name: payloadrepro-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=payloadrepro
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes: 
      - data:/var/lib/postgresql/data
    networks:
      - payloadrepro
volumes:
  data:
    

networks:
  payloadrepro:
    name: payloadrepro
